# Generated by Django 3.1.1 on 2020-09-06 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=patient.models.increment_card_number, editable=False, max_length=20)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('middle', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=('Female', 'Female'), max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(default='', max_length=64)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('appointment', models.DateField(blank=True)),
                ('created_by', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
