# Generated by Django 3.1.1 on 2020-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20201003_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='Addis Ababa', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='Ethiopia', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_city',
            field=models.CharField(blank=True, choices=[('Addis Ketema', 'Addis Ketema'), ('Akaki Kaliti', 'Akaki Kaliti'), ('Arada', 'Arada'), ('Bole', 'Bole'), ('Gullele', 'Gullele'), ('Kirkos', 'Kirkos'), ('Kolfe Keranio', 'Kolfe Keranio'), ('Lideta', 'Lideta'), ('Nefassilk', 'Nefas Silk'), ('Yeka', 'Yeka')], default=None, max_length=20, null=True),
        ),
    ]
