# Generated by Django 3.1.1 on 2020-10-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20201004_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_of',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patient.address'),
        ),
    ]
