# Generated by Django 3.1.1 on 2020-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20201005_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(blank=True, max_length=64, null=True)),
                ('middle', models.CharField(blank=True, max_length=64, null=True)),
                ('specialised', models.CharField(blank=True, max_length=65, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
