# Generated by Django 3.1.1 on 2020-10-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20201011_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appoiment',
            new_name='Appointment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='appointment',
        ),
    ]
