# Generated by Django 3.1.1 on 2020-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20201031_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
