# Generated by Django 3.1.1 on 2020-11-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20201101_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last',
            new_name='middlename',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='middle',
            new_name='surname',
        ),
    ]
