# Generated by Django 3.1.1 on 2020-11-01 18:17

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20201101_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
