# Generated by Django 3.1.1 on 2020-11-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_auto_20201101_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
