# Generated by Django 3.1.1 on 2020-11-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_auto_20201101_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
