# Generated by Django 3.1.1 on 2020-11-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20201104_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
    ]
